erDiagram
    ISIK ||--|| KASUTAJAKONTO : "omab"
    KASUTAJAKONTO ||--o| TOOTAJA : "võib olla"
    KASUTAJAKONTO ||--o| KLIENT : "võib olla"
    TOOTAJA ||--o{ TOOTAJA_ROLLI_OMAMINE : "rollid"
    TOOTAJA_ROLL ||--o{ TOOTAJA_ROLLI_OMAMINE : "määrab"

    TREENINGULIIK ||--o{ TREENINGUKORD : "põhineb liigile"
    TREENINGULIIK ||--o{ TREENERI_PADEVUS : "määrab vajaliku pädevuse"
    TREENINGULIIK ||--o{ TREENINGULIIGI_VARUSTUSE_NOUE : "nõuab varustust"
    TOOTAJA ||--o{ TREENERI_PADEVUS : "omab pädevust"
    TOOTAJA ||--o{ TREENINGUKORD : "juhendab"
    RUUM ||--o{ TREENINGUKORD : "toimub ruumis"
    RUUM ||--o{ RUUMI_VARUSTUSE_OMAMINE : "sisaldab varustust"
    VARUSTUS ||--o{ RUUMI_VARUSTUSE_OMAMINE : "on ruumis"
    VARUSTUS ||--o{ TREENINGULIIGI_VARUSTUSE_NOUE : "kirjeldab nõuet"
    TREENINGUKORD }o--o{ RUUMI_VARUSTUSE_OMAMINE : "kontrollib sobivust"
    TREENINGUKORD }o--o{ TREENINGULIIGI_VARUSTUSE_NOUE : "kontrollib sobivust"

    TREENINGUKORD ||--o{ REGISTREERING : "võtab registreeringuid"
    KLIENT ||--o{ REGISTREERING : "registreerub"
    REGISTREERING ||--o| OOTEJARJEKORRA_KOHT : "saab järjekorrakoha"
    TREENINGUKORD ||--o{ OOTEJARJEKORRA_KOHT : "järjestab ootel registreeringud"
    REGISTREERING ||--o| OSALEMINE : "omab osalemise tulemust"

    TREENINGULIIGI_SEISUNDI_LIIK ||--o{ TREENINGULIIK : "kirjeldab liigi seisundit"
    TREENINGUKORRA_SEISUNDI_LIIK ||--o{ TREENINGUKORD : "kirjeldab korra seisundit"
    REGISTREERINGU_SEISUNDI_LIIK ||--o{ REGISTREERING : "kirjeldab registreeringu seisundit"

    TREENINGULIIK {
        int treeninguliigi_id PK
        string nimetus UK
        int kestus_minutites
        string treeninguliigi_seisundi_kood FK
    }
    TREENINGUKORD {
        int treeningukorra_id PK
        int treeninguliigi_id FK
        string treener_e_meil FK
        string ruumi_kood FK
        datetime alguse_aeg
        datetime lopu_aeg
        int maksimaalne_osalejate_arv
        string treeningukorra_seisundi_kood FK
    }
    VARUSTUS {
        string varustuse_kood PK
        string nimetus UK
        boolean on_aktiivne
    }
    RUUMI_VARUSTUSE_OMAMINE {
        string ruumi_kood PK, FK
        string varustuse_kood PK, FK
        int kogus
    }
    TREENINGULIIGI_VARUSTUSE_NOUE {
        int treeninguliigi_id PK, FK
        string varustuse_kood PK, FK
        int minimaalne_kogus
        boolean on_kohustuslik
    }
    REGISTREERING {
        int registreeringu_id PK
        int treeningukorra_id FK
        string klient_e_meil FK
        string registreeringu_seisundi_kood FK
    }
    OOTEJARJEKORRA_KOHT {
        int registreeringu_id PK, FK
        int treeningukorra_id FK
        int ootejarjekorra_nr UK
    }
    OSALEMINE {
        int registreeringu_id PK, FK
        boolean on_osalenud
        string markija_e_meil FK
    }
