erDiagram
    ISIK ||--o| TOOTAJA : "võib olla töötaja"
    ISIK ||--o| KLIENT : "võib olla klient"
    TOOTAJA ||--o| TREENER : "võib spetsialiseeruda"
    TREENER ||--o{ TREENINGUKORD : "juhendab"
    TREENER ||--o{ TREENERI_PADEVUS : "omab"
    TREENINGULIIK ||--o{ TREENERI_PADEVUS : "määrab sobivuse"
    KLIENT ||--o{ REGISTREERING : "esitab"
    TREENINGUKORD ||--o{ REGISTREERING : "kogub"
    REGISTREERING ||--o| OOTEJARJEKORRA_KOHT : "võib saada"
    REGISTREERING ||--o| OSALEMINE : "võib lõppeda"
    TREENINGULIIK ||--o{ TREENINGUKORD : "on aluseks"
    RUUM ||--o{ TREENINGUKORD : "võimaldab"
    KLASSIFIKAATOR ||--o{ SEISUND : "täpsustab liiki"
    SEISUND ||--o{ REGISTREERING : "kirjeldab hetkeseisu"
    SEISUND ||--o{ TREENINGUKORD : "kirjeldab hetkeseisu"
    SEISUND ||--o{ TREENINGULIIK : "kirjeldab kasutatavust"

    ISIK {
        tunnus e_meil
        tunnus isikukood
        nimetus eesnimi
        nimetus perenimi
        kirjeldus elukoht
        seisund isiku_seisund
    }
    TOOTAJA {
        tunnus tootaja_tunnus
        seisund tootaja_seisund
    }
    TREENER {
        tunnus treeneri_tunnus
        aeg rolli_kehtivus
        kirjeldus padevuste_ulatus
    }
    KLIENT {
        tunnus kliendi_tunnus
        tunnus aktiivsus
    }
    TREENINGUKORD {
        tunnus treeningukorra_tunnus
        aeg algus_ja_lopp
        aeg registreerimise_tahtaeg
        arv kohtade_piir
        seisund treeningukorra_seisund
    }
    REGISTREERING {
        tunnus registreeringu_tunnus
        aeg esitamise_aeg
        seisund registreeringu_seisund
        aeg tyhistamise_aeg
        aeg edendamise_aeg
    }
    OOTEJARJEKORRA_KOHT {
        arv jarjekorranumber
    }
    OSALEMINE {
        tunnus osalemise_tulemus
        aeg markimise_aeg
        kirjeldus markus
    }
    TREENINGULIIK {
        nimetus nimetus
        kirjeldus sisu
        aeg tyypiline_kestus
        seisund kasutatavus
    }
    TREENERI_PADEVUS {
        aeg kehtiv_alates
        aeg kehtiv_kuni
    }
    RUUM {
        tunnus ruumi_tunnus
        nimetus nimetus
        arv mahutavus
    }
    SEISUND {
        tunnus kood
        nimetus nimetus
        kirjeldus tahendus
    }
    KLASSIFIKAATOR {
        tunnus kood
        nimetus nimetus
        kirjeldus tahendus
        tunnus aktiivsus
    }
