erDiagram
    SEISUND {
        tunnus kood
        nimetus nimetus
        kirjeldus tahendus
        tunnus aktiivsus
    }
    ROLL {
        tunnus kood
        nimetus nimetus
        kirjeldus vastutus
        tunnus aktiivsus
    }
    RIIK {
        tunnus kood
        nimetus nimetus
        tunnus aktiivsus
    }
